version: '3.8'
services:
  student_db:
    container_name: student-db
    image: postgres:latest
    environment:
      POSTGRES_USER: student_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: student_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      local_internal:
        ipv4_address: 10.7.0.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student_user -d student_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    
  pgadmin:
    container_name: student-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      local_internal:
        ipv4_address: 10.7.0.3
volumes:
  postgres_data:
networks:
  local_internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.0.0/16
          gateway: 10.7.0.1
